version: '2.1'
services:  
  rabbitmq:    
    image: rabbitmq:3-management    
    container_name: 'rabbitmq'
    ports:         
      - 5672:5672
      - 15672:15672 
  db:
    image: "mcr.microsoft.com/mssql/server"   
    environment:
        SA_PASSWORD: "passPabloJobSity123!"
        ACCEPT_EULA: "Y"
    ports:         
      - 5004:1433
    healthcheck:
        test: ["CMD", "/opt/mssql-tools/bin/sqlcmd", "-Usa", "-PpassPabloJobSity123!", "-Q", "select 1"]
        interval: 1s
        retries: 20

  jobsity-chat-bot:   
    ports: 
      - 5002:80
    depends_on: 
      - rabbitmq            
    environment:
        ASPNETCORE_ENVIRONMENT: "Docker" 
    build:
      context: ./
      dockerfile: JobSityChat.Bot/Dockerfile

  jobsity-chat:
    ports: 
      - 5001:80
    depends_on: 
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_started
    environment:
      ASPNETCORE_ENVIRONMENT: "Docker"
    build:
      context: ./
      dockerfile: JobSityChat.Web/Dockerfile